name: mvc_rev004
configuration_name: default 190127
parts:
- guid: origin
  machine_position: 0.0
- guid: lds_coat
  machine_position: 0.0
- guid: btrn-dryer-mp1-001
  machine_position: 0.7000000000000001
- guid: btrn-dryer-zone-001
  machine_position: 2.32
- guid: btrn-dryer-zone-002
  machine_position: 3.5
- guid: btrn-dryer-zone-003
  machine_position: 4.68
- guid: btrn-dryer-zone-004
  machine_position: 5.86
- guid: btrn-dryer-zone-005
  machine_position: 7.04
- guid: lds_2d
  machine_position: 9.88
- guid: btrn-heater-00001
  machine_position: 2.48
  heater_type:
- guid: btrn-heater-00002
  machine_position: 2.77
  heater_type:
- guid: btrn-heater-00003
  machine_position: 3.06
  heater_type:
- guid: btrn-heater-00004
  machine_position: 3.36
  heater_type:
- guid: btrn-heater-00005
  machine_position: 3.66
  heater_type:
- guid: btrn-heater-00006
  machine_position: 3.95
  heater_type:
- guid: btrn-heater-00007
  machine_position: 4.24
  heater_type:
- guid: btrn-heater-00008
  machine_position: 4.54
  heater_type:
- guid: btrn-heater-00009
  machine_position: 4.84
  heater_type:
- guid: btrn-heater-00010
  machine_position: 5.13
  heater_type:
- guid: btrn-heater-00011
  machine_position: 5.42
  heater_type:
- guid: btrn-heater-00012
  machine_position: 5.72
  heater_type:
- guid: btrn-heater-00013
  machine_position: 6.0200000000000005
  heater_type:
- guid: btrn-heater-00014
  machine_position: 6.3100000000000005
  heater_type:
- guid: btrn-heater-00015
  machine_position: 6.6000000000000005
  heater_type:
- guid: btrn-heater-00016
  machine_position: 6.9
  heater_type:
- guid: btrn-heater-00017
  machine_position: 7.2
  heater_type:
- guid: btrn-heater-00018
  machine_position: 7.49
  heater_type:
- guid: btrn-heater-00019
  machine_position: 7.78
  heater_type:
- guid: btrn-heater-00020
  machine_position: 8.08
  heater_type:
- guid: btrn-mp1-hg00001
  machine_position: 1.5
  heater_type:
- guid: btrn-mp1-hg00002
  machine_position: 1.85
  heater_type:
- guid: btrn-temp-sensor-000007
  machine_position: 1.65
  color:
  - 0.86
  - 0.3712
  - 0.33999999999999997
- guid: btrn-temp-sensor-000008
  machine_position: 2.0
  color:
  - 0.86
  - 0.7612000000000001
  - 0.33999999999999997
- guid: btrn-temp-sensor-000001
  machine_position: 2.62
  color:
  - 0.5688000000000001
  - 0.86
  - 0.33999999999999997
- guid: btrn-temp-sensor-000002
  machine_position: 3.8
  color:
  - 0.33999999999999997
  - 0.86
  - 0.5012000000000001
- guid: btrn-temp-sensor-000003
  machine_position: 4.98
  color:
  - 0.33999999999999997
  - 0.8287999999999999
  - 0.86
- guid: btrn-temp-sensor-000004
  machine_position: 6.16
  color:
  - 0.33999999999999997
  - 0.43879999999999986
  - 0.86
- guid: btrn-temp-sensor-000005
  machine_position: 7.34
  color:
  - 0.6311999999999998
  - 0.33999999999999997
  - 0.86
- guid: btrn-temp-sensor-000006
  machine_position: 8.33
  color:
  - 0.86
  - 0.33999999999999997
  - 0.6987999999999996
heater_guids:
- btrn-heater-00001
- btrn-heater-00002
- btrn-heater-00003
- btrn-heater-00004
- btrn-heater-00005
- btrn-heater-00006
- btrn-heater-00007
- btrn-heater-00008
- btrn-heater-00009
- btrn-heater-00010
- btrn-heater-00011
- btrn-heater-00012
- btrn-heater-00013
- btrn-heater-00014
- btrn-heater-00015
- btrn-heater-00016
- btrn-heater-00017
- btrn-heater-00018
- btrn-heater-00019
- btrn-heater-00020
mp1_heater_guids:
- btrn-mp1-hg00001
- btrn-mp1-hg00002
